{
  added_products: [
    {
      id: 2,
      title: "Anagya Podi",
      category: "Rasam & Soup",
      image: item,
      size: "250g",
      unit_price: "150",
      quantity: "2",
      price: "300",
    },
    {
      id: 4,
      title: "HealthMix Dosa",
      category: "Health Mix",
      image: item,
      size: "200g",
      unit_price: "100",
      quantity: "1",
      price: "100",
    },
    {
      id: 2,
      title: "Anagya Podi",
      category: "Rasam & Soup",
      image: item,
      size: "250g",
      unit_price: "150",
      quantity: "2",
      price: "300",
    },
    {
      id: 2,
      title: "HealthMix Dosa",
      category: "Health Mix",
      image: item,
      size: "200g",
      unit_price: "100",
      quantity: "1",
      price: "100",
    },
  ];
  all_products: [
    {
      id: "1",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "2",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g", "1kg"],
      price: ["110", "170", "280", "460"],
    },
    {
      id: "3",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "4",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "5",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "6",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g", "1kg"],
      price: ["110", "170", "280", "460"],
    },
    {
      id: "7",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "8",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "9",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "10",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "11",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "12",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g", "1kg"],
      price: ["110", "170", "280", "460"],
    },
    {
      id: "13",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "14",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "15",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "16",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "17",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
    {
      id: "18",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g", "500g", "1kg"],
      price: ["110", "170", "280", "460"],
    },
    {
      id: "19",
      title: "Multigrain Health Mix",
      image: item,
      category: "Health Mix",
      unit_price: "110",
      size: ["200g", "250g", "500g"],
      price: ["110", "170", "280"],
    },
    {
      id: "20",
      title: "Desi Chai Masala",
      image: item,
      category: "Beverage Mixes",
      unit_price: "110",
      size: ["200g", "250g"],
      price: ["110", "170"],
    },
  ];
}
