# Generated by Django 4.0.3 on 2023-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone_code', models.TextField()),
                ('phone_no', models.TextField()),
                ('password', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
    ]
