# Generated by Django 4.0.3 on 2023-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_realvedic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actionLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('log_message', models.TextField()),
                ('date_time', models.TextField(default='2023-03-06 15:46:49.805945+05:30')),
            ],
        ),
    ]
