# Generated by Django 4.0.3 on 2023-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_realvedic_app', '0002_actionlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogs',
            name='date_time',
            field=models.TextField(default='2023-03-08 17:41:54.250570+05:30'),
        ),
    ]
