# Generated by Django 4.1.5 on 2023-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('order_date', models.TextField()),
                ('seller_id', models.TextField()),
                ('Product_id', models.TextField()),
                ('Total_amount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.TextField()),
                ('Product_name', models.TextField()),
                ('category', models.TextField()),
                ('image', models.TextField()),
                ('prize', models.TextField()),
                ('Variant', models.TextField()),
                ('Status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.TextField()),
                ('seller_name', models.TextField()),
                ('email', models.TextField()),
                ('contact', models.TextField()),
                ('Address_line1', models.TextField()),
                ('Address_line2', models.TextField()),
                ('city', models.TextField()),
                ('pincode', models.TextField()),
                ('state', models.TextField()),
                ('Country', models.TextField()),
            ],
        ),
    ]
