# Generated by Django 4.1.5 on 2023-01-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.TextField()),
                ('customer_name', models.TextField()),
                ('email', models.TextField()),
                ('contact', models.TextField()),
                ('Address_line1', models.TextField()),
                ('Address_line2', models.TextField()),
                ('city', models.TextField()),
                ('pincode', models.TextField()),
                ('state', models.TextField()),
                ('Country', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Seller_details',
        ),
        migrations.RenameField(
            model_name='order_data',
            old_name='seller_id',
            new_name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='product_data',
            name='Variant',
        ),
        migrations.RemoveField(
            model_name='product_data',
            name='prize',
        ),
        migrations.AddField(
            model_name='product_data',
            name='HSN',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='SKU',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='Sizes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='how_to_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='how_we_make_it',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='nutrition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='prices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product_data',
            name='sibling_product',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='Product_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='Product_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='Status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_data',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
