# Generated by Django 4.1.5 on 2023-01-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0002_customer_details_delete_seller_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_data',
            name='image',
        ),
    ]
