# Generated by Django 4.1.5 on 2023-01-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0005_alter_category_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_data',
        ),
    ]
