# Generated by Django 4.1.5 on 2023-01-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0007_product_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categoryy',
        ),
    ]
