# Generated by Django 4.1.5 on 2023-01-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0009_images_and_banners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images_and_banners',
        ),
    ]
