# Generated by Django 4.1.5 on 2023-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0011_images_and_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
