# Generated by Django 4.1.5 on 2023-01-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0013_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Points',
            field=models.TextField(blank=True),
        ),
    ]
