# Generated by Django 4.1.5 on 2023-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0014_blogs_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='Product_id',
            field=models.TextField(auto_created=True, blank=True),
        ),
    ]
