# Generated by Django 4.1.5 on 2023-01-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0015_alter_product_data_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_data',
            name='Product_id',
        ),
    ]
