# Generated by Django 4.1.5 on 2023-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0016_remove_product_data_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_and_banners',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
