# Generated by Django 4.1.5 on 2023-01-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0018_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
