# Generated by Django 4.1.5 on 2023-02-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0019_alter_product_data_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_data',
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='product_data',
            old_name='prices',
            new_name='price',
        ),
    ]
