# Generated by Django 4.1.5 on 2023-02-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0020_rename_sizes_product_data_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_data',
            old_name='Size',
            new_name='size',
        ),
    ]
