# Generated by Django 4.1.5 on 2023-02-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0021_rename_size_product_data_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_data',
            old_name='Product_name',
            new_name='title',
        ),
    ]
