# Generated by Django 4.1.5 on 2023-02-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0022_rename_product_name_product_data_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('add_line_1', models.TextField()),
                ('add_line_2', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('pincode', models.TextField()),
                ('phone_no', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('product_id', models.TextField()),
                ('size', models.TextField()),
                ('quantity', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
                ('dob', models.TextField()),
                ('phone_code', models.TextField()),
                ('phone_no', models.TextField()),
                ('password', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
    ]
