# Generated by Django 4.1.5 on 2023-02-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0026_paymentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('speciality', models.TextField(blank=True)),
                ('available', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
