# Generated by Django 4.1.5 on 2023-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0028_alter_doctor_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryy',
            name='category_banner',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
