# Generated by Django 4.1.5 on 2023-02-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0029_categoryy_category_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_data',
            old_name='Customer_id',
            new_name='size',
        ),
        migrations.AddField(
            model_name='order_data',
            name='price_per_unit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order_data',
            name='quantity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order_data',
            name='user_id',
            field=models.TextField(null=True),
        ),
    ]
