# Generated by Django 4.1.5 on 2023-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0031_paymentorder_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='Product_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='Total_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='order_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='price_per_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='quantity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
