# Generated by Django 4.1.5 on 2023-02-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0032_alter_order_data_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='order_date',
        ),
    ]
