# Generated by Django 4.1.5 on 2023-02-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0033_remove_order_data_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='placed_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order_data',
            name='status',
            field=models.CharField(choices=[('placed', 'PLACED'), ('Ready to dispatch', 'READY TO DISPATCH'), ('dispatched', 'DISPATCHED'), ('on the way', 'On the way'), ('delivered', 'DELIVERED'), ('CANCELLED', 'cancelled'), ('RETURNED', 'returned')], default='Placed', max_length=50),
        ),
    ]
