# Generated by Django 4.1.5 on 2023-02-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0034_order_data_placed_at_order_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
