# Generated by Django 4.1.5 on 2023-02-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0035_order_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_cart',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
