# Generated by Django 4.1.5 on 2023-02-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0036_user_cart_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_data',
            old_name='Product_id',
            new_name='product_details',
        ),
        migrations.RemoveField(
            model_name='order_data',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order_data',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='order_data',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order_data',
            name='size',
        ),
    ]
