# Generated by Django 4.1.5 on 2023-02-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0037_rename_product_id_order_data_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='status',
            field=models.CharField(choices=[('placed', 'PLACED'), ('Processed', 'processed'), ('dispatched', 'DISPATCHED'), ('on the way', 'On the way'), ('delivered', 'DELIVERED'), ('CANCELLED', 'cancelled'), ('RETURNED', 'returned')], default='Placed', max_length=50),
        ),
    ]
