# Generated by Django 4.1.5 on 2023-02-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0038_alter_order_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cart',
            name='quantity',
            field=models.TextField(default=0),
        ),
    ]
