# Generated by Django 4.1.6 on 2023-02-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0039_alter_user_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_data',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
