# Generated by Django 4.1.6 on 2023-02-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0040_alter_product_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_and_banners',
            name='image',
            field=models.TextField(),
        ),
    ]
