# Generated by Django 4.1.6 on 2023-02-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0041_alter_images_and_banners_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryy',
            name='category_banner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categoryy',
            name='category_image',
            field=models.TextField(),
        ),
    ]
