# Generated by Django 4.1.6 on 2023-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0042_alter_categoryy_category_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
