# Generated by Django 4.1.6 on 2023-02-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0043_product_data_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor_info',
            name='image',
            field=models.TextField(),
        ),
    ]
