# Generated by Django 4.0.3 on 2023-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0044_alter_blogs_image_alter_doctor_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_and_banners',
            name='product_id',
            field=models.TextField(blank=True),
        ),
    ]
