# Generated by Django 4.0.3 on 2023-02-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0048_alter_nologinuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='add_line_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='country',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='phone_no',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='pincode',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='state',
            field=models.TextField(blank=True),
        ),
    ]
