# Generated by Django 4.0.3 on 2023-02-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0049_alter_user_address_add_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentorder',
            old_name='token',
            new_name='user_id',
        ),
    ]
