# Generated by Django 4.0.3 on 2023-02-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0051_paymentorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_amount',
            field=models.TextField(max_length=25),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_payment_id',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_product',
            field=models.TextField(max_length=100),
        ),
    ]
