# Generated by Django 4.0.3 on 2023-02-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0053_alter_paymentorder_order_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryy',
            name='category_banner_mobile',
            field=models.TextField(default='media/'),
            preserve_default=False,
        ),
    ]
