# Generated by Django 4.0.3 on 2023-02-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0054_categoryy_category_banner_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_data',
            name='tax',
            field=models.TextField(default=15),
            preserve_default=False,
        ),
    ]
