# Generated by Django 4.0.3 on 2023-02-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0056_remove_product_data_status_product_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
