# Generated by Django 4.0.3 on 2023-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0059_alter_paymentorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-02-28 14:05:24.185957+05:30'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-02-28 14:05:24.185957+05:30'),
        ),
    ]
