# Generated by Django 4.0.3 on 2023-03-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0060_user_data_created_at_alter_paymentorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-01 10:37:59.909565+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-01 10:37:59.909565+05:30'),
        ),
    ]
