# Generated by Django 4.0.3 on 2023-03-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0061_user_data_status_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='admin_create_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-01 11:31:41.028686+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-01 11:31:41.028686+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='token',
            field=models.TextField(blank=True),
        ),
    ]
