# Generated by Django 4.0.3 on 2023-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0062_user_data_admin_create_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='admin_placed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-01 19:03:38.988961+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-01 19:03:38.987985+05:30'),
        ),
    ]
