# Generated by Django 4.0.3 on 2023-03-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0065_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_data',
            name='admin_placed_status',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='admin_placed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-01 19:08:44.149001+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-01 19:08:44.146998+05:30'),
        ),
    ]
