# Generated by Django 4.0.3 on 2023-03-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0066_remove_order_data_admin_placed_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-02 11:20:54.106707+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-02 11:20:54.105682+05:30'),
        ),
    ]
