# Generated by Django 4.0.3 on 2023-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0067_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_and_banners',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-02 17:01:26.949073+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-02 17:01:26.949073+05:30'),
        ),
    ]
