# Generated by Django 4.0.3 on 2023-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0068_images_and_banners_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images_and_banners',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-02 17:02:19.314702+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-02 17:02:19.314702+05:30'),
        ),
    ]
