# Generated by Django 4.0.3 on 2023-03-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0070_images_and_banners_mobile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_and_banners',
            name='discount',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-03 15:02:07.591924+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-03 15:02:07.591924+05:30'),
        ),
    ]
