# Generated by Django 4.0.3 on 2023-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0071_images_and_banners_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-06 11:05:59.773766+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-06 11:05:59.773766+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='dob',
            field=models.TextField(blank=True),
        ),
    ]
