# Generated by Django 4.0.3 on 2023-03-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realvedic_app', '0072_alter_paymentorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryy',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_date',
            field=models.TextField(default='2023-03-06 12:09:25.410317+05:30'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='created_at',
            field=models.TextField(default='2023-03-06 12:09:25.410317+05:30'),
        ),
    ]
